
#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    ".zpkg.toml",
    ".node-version",
    ".tool-versions",
    "rust-toolchain.toml",
    ".github/workflows/scaffold.yml",
    "contracts/schema-lock.json",
    "packages/rust/Cargo.toml",
    "packages/typescript/package.json",
    "packages/dart/pubspec.yaml",
    "packages/gleam/gleam.toml",
    "tooling/schema-codegen/Cargo.toml",
    "tooling/conformance/run.py",
]
GENERATED = [
    "packages/rust/crates/ore-mcp-contracts/src/generated/result_envelope.rs",
    "packages/typescript/src/generated/result-envelope.ts",
    "packages/typescript/dist/generated/result-envelope.js",
    "packages/typescript/dist/generated/result-envelope.d.ts",
    "packages/dart/lib/src/generated/result_envelope.dart",
    "packages/gleam/src/ore_mcp_contracts/generated/result_envelope.gleam",
]
FORBIDDEN_MARKERS = ["<<<<<<< ", "=======\n", ">>>>>>> ", "BEGIN PRIVATE KEY", "BEGIN OPENSSH PRIVATE KEY"]


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def main() -> int:
    for relative in REQUIRED:
        if not (ROOT / relative).is_file():
            fail(f"missing required file: {relative}")

    manifest = tomllib.loads((ROOT / ".zpkg.toml").read_text())
    if manifest.get("package", {}).get("org") != "oresoftware":
        fail("unexpected Zed package organization")
    targets = manifest.get("targets", {})
    if set(targets) != {"rust", "nodejs", "dart", "gleam"}:
        fail("Zed manifest must declare exactly rust/nodejs/dart/gleam targets")
    for name, target in targets.items():
        path = ROOT / target["dir"]
        if not path.is_dir() or not path.resolve().is_relative_to(ROOT.resolve()):
            fail(f"invalid target directory for {name}")

    lock = json.loads((ROOT / "contracts/schema-lock.json").read_text())
    if len(lock.get("schemas", [])) != 1:
        fail("scaffold expects one initial schema")
    entry = lock["schemas"][0]
    schema_path = ROOT / entry["path"]
    digest = hashlib.sha256(schema_path.read_bytes()).hexdigest()
    if digest != entry["sha256"]:
        fail("schema-lock digest mismatch")
    for relative in GENERATED:
        text = (ROOT / relative).read_text()
        if digest not in text or "@generated by ore-mcp-codegen" not in text:
            fail(f"generated provenance mismatch: {relative}")

    generator_map = json.loads((ROOT / "tooling/schema-codegen/generator-map.json").read_text())
    if generator_map.get("format") != "ore-mcp-generator-map/v1":
        fail("unexpected generator-map format")
    replacements = {
        "{{GENERATOR_VERSION}}": lock["generator"]["version"],
        "{{SCHEMA_ID}}": json.loads(schema_path.read_text())["$id"],
        "{{SCHEMA_SHA256}}": digest,
    }
    mapped_outputs = set()
    for item in generator_map.get("outputs", []):
        template_path = ROOT / item["template"]
        output_path = ROOT / item["output"]
        if not template_path.is_file() or not output_path.is_file():
            fail("generator-map references a missing template or output")
        rendered = template_path.read_text()
        for placeholder, value in replacements.items():
            rendered = rendered.replace(placeholder, value)
        if re.search(r"\{\{[A-Z][A-Z0-9_]*\}\}", rendered):
            fail(f"unresolved generator placeholder: {item['template']}")
        if output_path.read_text() != rendered:
            fail(f"generated output drift: {item['output']}")
        mapped_outputs.add(item["output"])
    if mapped_outputs != set(GENERATED):
        fail("generator-map output set drift")

    symlinks = [path for path in ROOT.rglob("*") if path.is_symlink()]
    if symlinks:
        fail(f"symlinks are not allowed in scaffold: {symlinks[0]}")

    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.resolve() == Path(__file__).resolve():
            continue
        if any(part in {"target", "node_modules", ".dart_tool", "_build", "deps", "__pycache__"} for part in path.parts) or path.suffix == ".pyc" or path.name == ".schema_digest":
            fail(f"build/cache path included: {path.relative_to(ROOT)}")
        try:
            text = path.read_text()
        except UnicodeDecodeError:
            continue
        for marker in FORBIDDEN_MARKERS:
            if marker in text:
                fail(f"forbidden marker in {path.relative_to(ROOT)}")
        if "/mnt/data/" in text:
            fail(f"local absolute path leaked into {path.relative_to(ROOT)}")

    fixture_roots = {
        "valid": ROOT / "contracts/examples/valid/result-envelope",
        "invalid": ROOT / "contracts/examples/invalid/result-envelope",
    }
    fixture_counts = {name: len(list(path.glob("*.json"))) for name, path in fixture_roots.items()}
    if fixture_counts["valid"] < 6 or fixture_counts["invalid"] < 30:
        fail(f"fixture corpus unexpectedly small: {fixture_counts}")
    if not (fixture_roots["valid"] / "unicode-codepoint-boundary.json").is_file():
        fail("missing Unicode code-point boundary fixture")
    if not (fixture_roots["invalid"] / "forbidden-control.json").is_file():
        fail("missing forbidden-control fixture")

    expectations = json.loads((ROOT / "contracts/examples/expectations.json").read_text())
    expected_fixture_ids = {
        f"{kind}/result-envelope/{path.name}"
        for kind, fixture_root in fixture_roots.items()
        for path in fixture_root.glob("*.json")
    }
    actual_fixture_ids = set(expectations.get("fixtures", {}))
    if actual_fixture_ids != expected_fixture_ids:
        fail("fixture expectations are missing or stale")

    package_json = json.loads((ROOT / "packages/typescript/package.json").read_text())
    if package_json.get("dependencies", {}).get("zod") is None:
        fail("TypeScript target must provide Zod runtime validation")
    cargo = tomllib.loads((ROOT / "packages/rust/Cargo.toml").read_text())
    members = set(cargo["workspace"]["members"])
    expected_crates = {
        "crates/ore-mcp",
        "crates/ore-mcp-config",
        "crates/ore-mcp-contracts",
        "crates/ore-mcp-http",
        "crates/ore-mcp-runtime",
        "crates/ore-mcp-safety",
        "crates/ore-mcp-telemetry",
        "crates/ore-mcp-testkit",
    }
    if members != expected_crates:
        fail("Rust workspace membership drift")

    workflow_text = (ROOT / ".github/workflows/scaffold.yml").read_text()
    action_refs = re.findall(r"^\s*uses:\s*[^@\s]+@([^\s#]+)", workflow_text, flags=re.MULTILINE)
    if not action_refs or any(re.fullmatch(r"[0-9a-f]{40}", ref) is None for ref in action_refs):
        fail("every GitHub Action must be pinned to a full commit SHA")

    for manifest_path in (ROOT / "packages/rust/crates").glob("*/Cargo.toml"):
        package_manifest = tomllib.loads(manifest_path.read_text())
        for dependency_name, dependency in package_manifest.get("dependencies", {}).items():
            if (
                dependency_name.startswith("ore-mcp-")
                and isinstance(dependency, dict)
                and "path" in dependency
                and dependency.get("version") not in {"0.1.0", "=0.1.0"}
            ):
                fail(f"internal Cargo dependency lacks publishable version: {manifest_path.relative_to(ROOT)}:{dependency_name}")

    workspace_dependencies = cargo.get("workspace", {}).get("dependencies", {})
    otlp = workspace_dependencies.get("opentelemetry-otlp", {})
    if not isinstance(otlp, dict) or otlp.get("default-features") is not False:
        fail("OpenTelemetry OTLP must disable unrelated default exporters")
    otlp_features = set(otlp.get("features", []))
    if not {"grpc-tonic", "metrics", "trace", "tls-ring", "tls-roots"}.issubset(otlp_features):
        fail("OpenTelemetry OTLP feature set lacks explicit gRPC/TLS support")

    http_source = (ROOT / "packages/rust/crates/ore-mcp-http/src/lib.rs").read_text()
    for required_policy in (".no_proxy()", "Policy::none()", "retry::never()"):
        if required_policy not in http_source:
            fail(f"public diagnostic HTTP policy drift: missing {required_policy}")

    print(f"scaffold checks passed; schema_sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
